# RuneStones Configuration File
lang: "en-US.yml"

# Control whether or not runes are dropped on death.
drop-on-death: false

# Rarity Controls
legendary:
  # The number of shards you get for shattering 1 rune.
  shatter-reward: 1
  # The number of shards it costs to forge 1 rune.
  forge-cost: 4
  # How long the rune takes to forge. (In minutes)
  forge-delay: 1440
epic:
  # The number of shards you get for shattering 1 rune.
  shatter-reward: 2
  # The number of shards it costs to forge 1 rune.
  forge-cost: 8
  # How long the rune takes to forge. (In minutes)
  forge-delay: 720
unique:
  # The number of shards you get for shattering 1 rune.
  shatter-reward: 3
  # The number of shards it costs to forge 1 rune.
  forge-cost: 12
  # How long the rune takes to forge. (In minutes)
  forge-delay: 180
normal:
  # The number of shards you get for shattering 1 rune.
  shatter-reward: 4
  # The number of shards it costs to forge 1 rune.
  forge-cost: 16
  # How long the rune takes to forge. (In minutes)
  forge-delay: 60
