name: RuneStone
version: ${project.version}
main: ru.ibusewinner.fundaily.runestones.RuneStone
api-version: 1.13
authors: [iBuseWinner]
description: RuneStones plugin for NewFunDaily 1.15.1
website: new.fdmc.pw
softdepend: [Vault]
commands:
  rs:
    description: RuneStones admin command.
  artifact:
    description: Open Rune GUI
  artifacts:
    aliases: [af]
    description: Shortcut to view runes.
  afbag:
    description: Open rune bag.
    aliases: [artifactsbag]
